services:
  web:
    container_name: django-docker
    build: .
    command: python3 django_api/manage.py runserver 0.0.0.0:8000
    working_dir: /code
    ports: ["8000:8000"]
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: django-docker-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-local:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d/
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  mysql-local: